### ISSUE TITLE
Проблема с подключением к курсам на html aacademy

### ISSUE THREAD

**Issue by avinell** [DSTU-frontend-practice-2021/Group-3#3]
Перехожу по данной вами ссылке на курсы, вроде как прожимаю "подключиться", но после переходя на "начать тренажер" меня просят оформить подписку.
![image](https://user-images.githubusercontent.com/86418028/123273606-7806cc00-d50b-11eb-80cf-4c8ef16a851c.png)

**Comment by ankormoreankor** [comment]
@avinell, здравствуйте!
Полный доступ к программе включается вручную. Это особенность интерфейса, который нам предоставили. Я стараюсь мониторить и вовремя включать всем добавившимся доступ, но могут быть задержки.
Проверьте, пожалуйста, появился ли у вас доступ. Если его так и нет, напишите ваше имя и фамилию и/или id в точности, как на сайте академии, я проверю доступ и постараюсь его вам предоставить.

**Comment by avinell** [comment]
@ankormoreankor, благодарю за ответ, доступ выдался, всё работает.
