### ISSUE TITLE
Надо ли проходить практики, которые идут после теории???

### ISSUE THREAD

**Issue by KinoGeroy** [DSTU-frontend-practice-2021/Group-3#4]
![image](https://user-images.githubusercontent.com/71070607/123507325-6ccdb080-d671-11eb-8d68-31dd6984e160.png)

**Comment by ankormoreankor** [comment]
Здравствуйте!
Нет, не обязательно. Практики нужны, чтобы закрепить полученные знания/навыки, но предлагаемые нами задания направлены на это же.

**Comment by KinoGeroy** [comment]
Спасибо за ответ!
