### ISSUE TITLE
html

### ISSUE THREAD

**Issue by urVeritas** [DSTU-frontend-practice-2021/Group-3#5]
Добрый день, у меня пропал доступ к курсам html academy, что мне делать?

**Comment by ankormoreankor** [comment]
Добрый день!
Проверил и включил доступы тем, у кого они не были ещё включены. Если доступ у вас ещё не появился, напишите, пожалуйста, ваш id или Имя и Фамилию как в академии, я проверю и постараюсь решить эту проблему.
